services:
  backend:
    image: backend-image:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: production
    ports:
      - "1234:1234"
      - "5000:5000"
    environment:
      - PGUSER
      - PGHOST
      - PGDATABASE
      - PGPASSWORD
      - PGPORT
      - PG_SECRET_KEY
      - JWT_SECRET
      - LOG_LEVEL
      - WORD2VEC_URL
      - WEBAPP_URL
      - PRICE_ID
      - STRIPE_PRIVATE_KEY
      - STRIPE_SECRET
      - SELF_HOSTED
    depends_on:
      migrate:
        condition: service_completed_successfully

  migrate:
    image: node:20-slim
    working_dir: /usr/src/app/backend
    environment:
      - PGUSER
      - PGHOST
      - PGDATABASE
      - PGPASSWORD
      - PGPORT
      - PG_SECRET_KEY
    command: >
      sh -c "npm install -g pnpm && 
            pnpm install
            pnpm dlx knex migrate:latest"
    volumes:
      - ./backend:/usr/src/app/backend

  frontend:
    image: frontend-image:latest
    build:
      context: .
      dockerfile: client/Dockerfile
      target: production
    environment:
      - APP_URL
      - VITE_SELF_HOSTED=${SELF_HOSTED}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  word2vec:
    build:
      context: ./word2vec
      dockerfile: Dockerfile
      target: production
    ports:
      - "5001:5001"

  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
