services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:${PGPORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      start_period: 0s
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: backend-image:latest
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: development
    ports:
      - "1234:1234"
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
      - ./packages:/usr/src/app/packages
    environment:
      - PGUSER
      - PGHOST
      - PGDATABASE
      - PGPASSWORD
      - PGPORT
      - PG_SECRET_KEY
      - JWT_SECRET
      - LOG_LEVEL
      - WORD2VEC_URL=http://word2vec:5001
      - WEBAPP_URL
      - PRICE_ID
      - STRIPE_PRIVATE_KEY
      - STRIPE_SECRET
      - SELF_HOSTED
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SECURE
      - SMTP_USER
      - SMTP_PASS
      - EMAIL_FROM

    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: frontend-image:latest
    build:
      context: .
      dockerfile: client/Dockerfile
      target: development
    environment:
      - APP_URL
      - VITE_SELF_HOSTED=${SELF_HOSTED}
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
      - /usr/src/app/packages/node_modules
      - ./packages:/usr/src/app/packages

  word2vec:
    build:
      context: ./word2vec
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./word2vec:/app
    ports:
      - "5001:5001"
    depends_on:
      - postgres

volumes:
  postgres-data: