name: Publish Docker Images

on:
  push:
    tags:
      - "v*" # Trigger the workflow on tag push
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./backend/Dockerfile
          target: production
          tags: ghcr.io/unsearchapp/unsearch/backend-image:latest
          push: true

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./client/Dockerfile
          target: production
          tags: ghcr.io/unsearchapp/unsearch/frontend-image:latest
          push: true
